export const users = [
  { id: 'u1', name: 'Ava Stone', handle: 'avastone', avatar: '', verified: true },
  { id: 'u2', name: 'Liam Fox', handle: 'liamfox', avatar: '', verified: false },
  { id: 'u3', name: 'Maya Rivers', handle: 'mayar', avatar: '', verified: true },
];

export const posts = [
  // Ava Stone (u1)
  {
    id: 'p1',
    userId: 'u1',
    postType: 'image',
    content: 'Exploring the new city skyline — love the colors at dusk. A quiet moment, a lot of perspective, and a little bit of motion to make it feel alive. Exploring the new city skyline — love the colors at dusk. A quiet moment, a lot of perspective, and a little bit of motion to make it feel alive.',
    img: '/assets/posts/img1.jpg',
    likes: 24,
    comments: 8,
    timestamp: '2h',
  },
  {
    id: 'p2',
    userId: 'u1',
    postType: 'text',
    content: 'Exploring the new city skyline — love the colors at dusk. A quiet moment, a lot of perspective, and a little bit of motion to make it feel alive. Exploring the new city skyline — love the colors at dusk. A quiet moment, a lot of perspective, and a little bit of motion to make it feel alive.',
    img: '/assets/posts/img2.jpg',
    likes: 24,
    comments: 8,
    timestamp: '2h',
  },
  {
    id: 'p3',
    userId: 'u1',
    postType: 'image',
    content: 'Exploring the new city skyline — love the colors at dusk. A quiet moment, a lot of perspective, and a little bit of motion to make it feel alive.',
    img: '/assets/posts/img3.jpg',
    likes: 24,
    comments: 8,
    timestamp: '2h',
  },
  {
    id: 'p4',
    userId: 'u1',
    postType: 'image',
    content: 'Exploring the new city skyline — love the colors at dusk. A quiet moment, a lot of perspective, and a little bit of motion to make it feel alive.',
    img: '/assets/posts/img4.jpg',
    likes: 24,
    comments: 8,
    timestamp: '2h',
  },
  {
    id: 'p5',
    userId: 'u1',
    postType: 'image',
    content: 'Exploring the new city skyline — love the colors at dusk. A quiet moment, a lot of perspective, and a little bit of motion to make it feel alive.',
    img: '/assets/posts/img5.jpg',
    likes: 24,
    comments: 8,
    timestamp: '2h',
  },
  // Liam Fox (u2)
  {
    id: 'p8',
    userId: 'u2',
    postType: 'image',
    content: "Quick thoughts on building better social UI: clarity > complexity.",
    img: '/assets/posts/img2.jpg',
    likes: 46,
    comments: 12,
    timestamp: '5h',
  },
  {
    id: 'p9',
    userId: 'u2',
    postType: 'text',
    content: "Working on an exciting new project. Stay tuned for updates!",
    img: '/assets/posts/img3.jpg',
    likes: 32,
    comments: 9,
    timestamp: '3h',
  },
  {
    id: 'p10',
    userId: 'u2',
    postType: 'image',
    content: "Love this new design direction.",
    img: '/assets/posts/img5.jpg',
    likes: 18,
    comments: 5,
    timestamp: '1h',
  },
  // Maya Rivers (u3)
  {
    id: 'p11',
    userId: 'u3',
    postType: 'image',
    content: 'Designing with motion feels like sculpting time. When the UI breathes, the product feels more human.',
    img: '/assets/posts/img1.jpg',
    likes: 12,
    comments: 4,
    timestamp: '1d',
  },
  {
    id: 'p12',
    userId: 'u3',
    postType: 'image',
    content: 'Just launched my new portfolio. Check it out and let me know what you think!',
    img: '/assets/posts/img4.jpg',
    likes: 55,
    comments: 20,
    timestamp: '6h',
  },
  {
    id: 'p13',
    userId: 'u3',
    postType: 'image',
    content: 'Inspired by nature today.',
    img: '/assets/posts/img2.jpg',
    likes: 28,
    comments: 10,
    timestamp: '4h',
  },
];
